version: '3.8'
services:
  mysql:
    image: mysql
    ports:
      - 23306:3306
    container_name: mysql-compose

  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: nginx-compose
    ports:
      - 5002:80
    
